CREATE DATABASE LIBRERIA
Go
DELETE FROM LIBRO

USE LIBRERIA
Go

--CAMBIANDO EL FORMATO DE LA FECHA.
SET DATEFORMAT DMY
Go

CREATE TABLE LIBRO(
       CODLIB VARCHAR(5) PRIMARY KEY NOT NULL,		
       TITULOLIB CHAR(32),		
       AUTORLIB  CHAR(24),		
       EDITOLIB  CHAR(13),		
       AREALIB   CHAR(9),
       FECHAREG  DATETIME ,
       PRECIOLIB NUMERIC(8,2),	
       NHOJASLIB INT,			
       ANOLIB    INT)
Go

CREATE TABLE LIBRO_BACKUP(
       CODLIB VARCHAR(5) PRIMARY KEY NOT NULL,		
       TITULOLIB CHAR(32),		
       AUTORLIB  CHAR(24),		
       EDITOLIB  CHAR(13),		
       AREALIB   CHAR(9),
       FECHAREG  DATETIME ,
       PRECIOLIB NUMERIC(8,2),	
       NHOJASLIB INT,			
       ANOLIB    INT)
Go


--INSERTANDO DATOS EN LA TABLA LIBRO
INSERT INTO LIBRO VALUES('1000','VISUAL FOX','RUBEN IGLESIAS', 'RAMA', 'LPROG','03/05/1997',60,489,1997)
INSERT INTO LIBRO VALUES('1001','POWER BUILDER 6.','RAMIRO HOOL', 'UNI','LPROG', '12/01/1999',80,410,1999)
INSERT INTO LIBRO VALUES('1002','ANALISIS Y DISEÑO DE SIST.','KENDALL & KENDALL','PRINTICE HALL','ANALISIS','15/09/1997',100,913,1997)
INSERT INTO LIBRO VALUES('1003','POWER BUILDER 6.','WILLIAM B. HEYS', 'QUE','LPROG','12/04/1999',150,843,1999)
INSERT INTO LIBRO VALUES('1004','VISUAL BASIC','CESAR BUSTAMANTE', 'GRAPPERU','LPROG','25/12/1997',35,390,1997)
INSERT INTO LIBRO VALUES('1005','VISUAL FOX PRO','LES & JHON PINTER','MC GRAWHILL','LPROG','11/12/1997',25,567,1997)
INSERT INTO LIBRO VALUES('1006','GUIA C++','JULIO VASQUEZ PARAGULLAS', 'UPSMP', 'LPROG','13/02/1997',50,780,1997)
INSERT INTO LIBRO VALUES('1007','MS C++','BECK ZARATIAN', 'MICROSOFT', 'LPROG', '12/03/1999',80,600,1999)
INSERT INTO LIBRO VALUES('1008','VISUAL FOX PRO 6.00','CESAR BUSTAMANTE', 'UNI','LPROG','15/10/1999',35,450,1999)
INSERT INTO LIBRO VALUES('1009','AUTOCAD 2000','J.A. TAJADURA J. LOPEZ','MC GRAW HILL','CAD','03/10/1998',40,480,1998)
INSERT INTO LIBRO VALUES('1010','EFECTOS COREL', 'ANOMINO', 'MACRO', 'ARTE', '03/05/1998',50,400,1998)
INSERT INTO LIBRO VALUES('1011','EL VENDEDOR MAS GRANDE DEL MUNDO','OG MANDINO','DIANA','LIDERAZGO','03/11/1968',15,121,1968)
INSERT INTO LIBRO VALUES('1012','EL PODER DEL CARISMA','MIGUEL ANGEL CORNEJO', 'ESTRELLA','LIDERAZGO','11/03/1992',15,123,1992)
INSERT INTO LIBRO VALUES('1013','7 HABITOS DE LA GENTE EFECTIVA','STEPHEN  R. COVER','PAIDOS','LIDERAZGO','13/06/1989',50,460,1989)
INSERT INTO LIBRO VALUES('1014','CRITERIOS EVA. PROY.','NASSIR SAPAG CHAIN','MC GRAW HILL','PROYECTOS','11/02/1997',10,144,1997)
INSERT INTO LIBRO VALUES('1015','COMO DIRIGIR MICRO EMP.','VICTOR ABAD G.', 'IPEDE','PROYECTOS','12/06/1995',10,110,1995)
INSERT INTO LIBRO VALUES('1016','LA MAGIA DE PENSAR EN GRANDE','DAVID JASEPH SCHWRTZ','HERREROS MEX','LIDERAZGO','13/12/1960',10,258,1960)
INSERT INTO LIBRO VALUES('1017','SQL SERVER VB','WILLIAM R. VAUGHN', 'MICROSOFT','LPROG','01/02/1999',60,1000,1999)
INSERT INTO LIBRO VALUES('1018','VISUAL FOX 6.00','MENACHEN BAZIAN', 'QUE', 'LPROG','12/08/1999',55,1000,1999)
INSERT INTO LIBRO VALUES('1019','INTELIGENCIA EMOCIONAL','DANIEL GOLEMAN', 'ZETA','LIDERAZGO','12/08/1999',48,396,1996)
INSERT INTO LIBRO VALUES('1020','LA TERCERA OLA','ALVIN TOFFLER','MC GRAW HILL','LIDERAZGO','11/07/1998',50,250,1998)
GO

-- Consultando la Tabla Libro.
SELECT * FROM LIBRO

-- EJEMPLO 1:

--CREANDO EL CURSOR
DECLARE @TITULO VARCHAR(100), @PRECIO REAL
DECLARE AUMENTA_PRECIO CURSOR FOR SELECT TITULOLIB, PRECIOLIB FROM LIBRO WHERE AREALIB='LPROG'
OPEN AUMENTA_PRECIO
FETCH AUMENTA_PRECIO INTO @TITULO, @PRECIO
WHILE @@fetch_status = 0
BEGIN
	PRINT @TITULO + ' ' + CONVERT(VARCHAR,@PRECIO) + '  PRECIO AUMENTADO EN S/.10.00 ->' + CONVERT(VARCHAR,@PRECIO + 10)
	FETCH AUMENTA_PRECIO INTO @TITULO, @PRECIO
END
CLOSE AUMENTA_PRECIO
DEALLOCATE AUMENTA_PRECIO
Go

--EJEMPLO 2
--CURSOR COPIA DE SEGURIDAD
DECLARE @COD VARCHAR(5), @TITULO CHAR(32),@AUTOR CHAR(24),@EDITO CHAR(13)
DECLARE @AREA CHAR(9), @FECHA DATETIME,@PRECIO NUMERIC(8,2),@NHOJAS INT,@ALIB INT
DECLARE RESPALDO_LIBRO CURSOR FOR SELECT * FROM LIBRO
OPEN RESPALDO_LIBRO
FETCH RESPALDO_LIBRO INTO @COD,@TITULO,@AUTOR,@EDITO,@AREA,@FECHA,@PRECIO,@NHOJAS,@ALIB
WHILE @@fetch_status = 0
BEGIN
	INSERT INTO LIBRO_BACKUP VALUES(@COD,@TITULO,@AUTOR,@EDITO,@AREA,@FECHA,@PRECIO,@NHOJAS,@ALIB)
	FETCH RESPALDO_LIBRO INTO @COD, @TITULO, @AUTOR, @EDITO, @AREA, @FECHA,@PRECIO,@NHOJAS,@ALIB
END
CLOSE RESPALDO_LIBRO
DEALLOCATE RESPALDO_LIBRO
Go

SELECT * FROM LIBRO_BACKUP
Go


-- EJEMPLO 3:
DECLARE @name VARCHAR(50) -- Nombre de Base de datos  
DECLARE @path VARCHAR(256) -- Ruta escogida para los archivos del backup  
DECLARE @fileName VARCHAR(256) -- Nombre del Archivo para el Backup  
DECLARE @fileDate VARCHAR(20) -- Utilizado para el nombre de archivo
SET @path = 'C:\Backup\'  
SELECT @fileDate = CONVERT(VARCHAR(20),GETDATE(),112) 
DECLARE db_cursor CURSOR FOR  SELECT name FROM MASTER.dbo.sysdatabases 
           WHERE name NOT IN ('master','model','msdb','tempdb','ReportServer','ReportServerTempDB')  
OPEN db_cursor   
FETCH NEXT FROM db_cursor INTO @name   
WHILE @@FETCH_STATUS = 0   
BEGIN   
       SET @fileName = @path + @name + '_' + @fileDate + '.BAK'  
       BACKUP DATABASE @name TO DISK = @fileName  
       FETCH NEXT FROM db_cursor INTO @name   
END   
CLOSE db_cursor   
DEALLOCATE db_cursor 
Go
